PACKAGES=(
    alsa-firmware
    android-tools
    android-udev-rules
    apr
    apr-util
    btop
    code
    dbus-x11
    distrobox
    docker-ce
    docker-ce-cli
    docker-buildx-plugin
    docker-compose-plugin
    ffmpeg
    ffmpeg-libs
    ffmpegthumbnailer
    firefox
    flatpak
    flatpak-spawn
    fuse
    fzf
    google-noto-fonts-all
    grub2-tools-extra
    heif-pixbuf-loader
    htop
    intel-vaapi-driver
    just
    kernel-tools
    libcamera
    libcamera-tools
    libcamera-gstreamer
    libcamera-ipa
    libfdk-aac
    libratbag-ratbagd
    libva-utils
    lshw
    mozilla-fira-mono-fonts
    nerd-fonts
    net-tools
    nvme-cli
    nvtop
    openrgb-udev-rules
    openssl
    oversteer-udev
    pam-u2f
    pam_yubico
    pamu2fcfg
    pipewire-libs-extra
    pipewire-plugin-libcamera
    powerstat
    smartmontools
    solaar-udev
    squashfs-tools
    symlinks
    tcpdump
    tmux
    traceroute
    vim
    wireguard-tools
    wl-clipboard
    yubikey-manager
    zstd
    hyprland
    kitty
    wofi
    vifm
)

rpm-ostree install "${PACKAGES[@]}"
